modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="remnents_of_rwby"
version="1.0.0"
displayName="Remnents of Rwby"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="kirby, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.remnents_of_rwby]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



